# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2014
  project: Address List for Calendar Events
  version: 1.0
  release: 1.0.8
  latex_documents:
  - - Index
    - addresslist4cal.tex
    - Address List for Calendar Events
    - Michael Oehlhof
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
